name: Release deploy           # workflow名字

on:                            # 触发条件，新建tag时触发
  push:
    tags:
      - '*'                   # 任意标签都会触发工作流

jobs:
  pkg:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Extract version
        id: extract_version
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"  
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ github.repository }}:${{ env.VERSION }}